BERT: {"dropout": 0.1, 
      "learning_rate": 0.00003, 
      "batch_size": 128, 
      "clipnorm": 1.0, 
      "epsilon": 0.00000001,
      "callback_monitor": "val_loss",
      "callback_patience": 5,
      "epochs": 20,
      "text_col": "cleaned_text",
      "target_col": "sentiment"}
topics: ["Drinks", "Snacks", "Ingredients", "Baked goods", "Sauces", "Cereal", "Noodles", "Pet"]
topic_mapping: {"Drinks": ['drinks', 'tea', 'coffee', 'juice', 'soda'], 
          "Snacks": ['snacks', 'nuts', 'chips', 'crackers', 'protein bars'], 
          "Ingredients": ['ingredients', 'sugar', 'salt', 'oil', 'seasoning', 'spices'],
          "Baked goods": ['baked goods', 'pastries', 'cookies'], 
          "Sauces": ['sauces', 'butter'], 
          "Cereal": ['cereal'], 
          "Noodles": ['noodles',  'pasta'], 
          "Pet": ['pet', 'dog', 'cat']}
custom_stopwords: ['great', 'taste', 'good', 'like', 'product', 'flavor', 'love', 'really', 'buy', 'tastes', 'better', 'best', 'tried', 'use', 'eat', 'food', 'make']
labels: ['drinks', 'snacks', 'ingredients', 'baked goods', 'spreads', 'noodles & pasta', 'pets']
