BERT:
  batch_size: 128
  callback_monitor: val_loss
  callback_patience: 5
  clipnorm: 1.0
  dropout: 0.1
  epochs: 20
  epsilon: 1.0e-08
  learning_rate: 3.0e-05
  target_col: sentiment
  text_col: cleaned_text
BERTopic:
  hdbscan_args:
    cluster_selection_method: leaf
    metric: euclidean
    min_cluster_size: 50
    prediction_data: true
  nr_topics: 27
  vectorizer_args:
    stop_words: english
  vectorizer_model: CountVectorizer
LDA:
  bi_min: 15
  common_words:
  - great
  - taste
  - good
  - like
  - product
  - flavor
  - love
  - really
  - buy
  - tastes
  - better
  - best
  - tried
  - use
  - eat
  - food
  - make
  - would
  - one
  - get
  - tea
  - coffee
  - price
  - amazon
  - bag
  - dog
  - cup
  - much
  min_prob: 0
  ngram: 2
  no_above: 0.5
  no_below: 15
  num_topics: 20
LOGREG:
  callback_patience: 5
  min_count: 2
  sg: 0
  target_col: sentiment
  text_col: cleaned_text_new
  vector_size: 100
  window: 5
LSTM:
  batch_size: 64
  epochs: 12
  input_length: 50
  learning_rate: 0.0005
  min_count: 2
  min_delta: 0.01
  patience: 3
  sg: 0
  target_col: sentiment
  text_col: cleaned_text_new
  vector_size: 100
  verbose: 2
  window: 5
NMF:
  nmf_args:
    init: nndsvd
    max_iter: 500
    n_components: 10
  vectorizer_args:
    max_df: 0.85
    max_features: 5000
    min_df: 3
bert_training_graph_filename: bert_training.png
best_sentiment_analysis_model: BERT
custom_stopwords:
- great
- taste
- good
- like
- product
- flavor
- love
- really
- buy
- tastes
- better
- best
- tried
- use
- eat
- food
- make
labels:
- Drinks
- Snacks
- Ingredients
- Flavour
- Baked Goods
- Noodles & Pasta
- Pet Food
lstm_training_acc_graph_filename: lstm_training_acc.png
lstm_training_loss_graph_filename: lstm_training_loss.png
metrics_filename: metrics.json
model_filename: model.pkl
output_path: data/predicted
processed_data_path: data/processed
raw_data_path: data/raw
sentiment_analysis_path: src/models/sentiment_analysis
test_filename: final_presentation/reviews_test.csv
topic_mapping:
  Baked Goods:
  - Baked Goods
  - Pastries
  - Cookies
  - Bread
  Drinks:
  - Drinks
  - Tea
  - Coffee
  - Juice
  - Soda
  Flavour:
  - Flavour
  - Flavor
  - Taste
  - Seasoning
  - Spices
  - Sauce
  - Chili
  Ingredients:
  - Ingredients
  - Sugar
  - Salt
  - Oil
  - Coconut
  - Olive
  - Cocoa
  - Cacao
  - Sweetener
  - Gluten
  Noodles & Pasta:
  - Noodles
  - Pasta
  - Ramen
  - Udon
  Pet Food:
  - Dog Food
  - Cat Food
  - Pet Food
  - Dog Treat
  Snacks:
  - Snacks
  - Nuts
  - Chips
  - Crackers
  - Protein Bars
  - Cereal
topic_modelling_path: src/models/topic_modelling
topics:
- Drinks
- Snacks
- Ingredients
- Flavour
- Baked Goods
- Noodles & Pasta
- Pet Food
train_filename: reviews.csv
