BERT: {"dropout": 0.1, 
      "learning_rate": 0.00003, 
      "batch_size": 128, 
      "clipnorm": 1.0, 
      "epsilon": 0.00000001,
      "callback_monitor": "val_loss",
      "callback_patience": 5,
      "epochs": 20,
      "text_col": "cleaned_text",
      "target_col": "sentiment"}
topics: ["Drinks", "Snacks", "Ingredients", "Baked Goods", "Spreads", "Noodles & Pasta", "Pets"]
topic_mapping: {"Drinks": ['drinks', 'tea', 'coffee', 'juice', 'soda'], 
          "Snacks": ['snacks', 'nuts', 'chips', 'crackers', 'protein bars', 'cereal'], 
          "Ingredients": ['ingredients', 'sugar', 'salt', 'oil', 'seasoning', 'spices'],
          "Baked Goods": ['baked', 'pastries', 'cookies'], 
          "Spreads": ['sauces', 'butter'],
          "Noodles & Pasta": ['noodles',  'pasta'], 
          "Pets": ['pet', 'dog', 'cat']}
custom_stopwords: ['great', 'taste', 'good', 'like', 'product', 'flavor', 'love', 'really', 'buy', 'tastes', 'better', 'best', 'tried', 'use', 'eat', 'food', 'make']
labels: ['Drinks', 'Snacks', 'Ingredients', 'Baked Goods', 'Spreads', 'Noodles & Pasta', 'Pets']
